<?php

return [
    // EU Countries
    'AT' => 'Austria',
    'BE' => 'Belgium',
    'BG' => 'Bulgaria',
    'HR' => 'Croatia',
    'CY' => 'Cyprus',
    'CZ' => 'Czech Republic',
    'DK' => 'Denmark',
    'EE' => 'Estonia',
    'FI' => 'Finland',
    'FR' => 'France',
    'DE' => 'Germany',
    'GR' => 'Greece',
    'HU' => 'Hungary',
    'IE' => 'Ireland',
    'IT' => 'Italy',
    'LV' => 'Latvia',
    'LT' => 'Lithuania',
    'LU' => 'Luxembourg',
    'MT' => 'Malta',
    'NL' => 'Netherlands',
    'PL' => 'Poland',
    'PT' => 'Portugal',
    'RO' => 'Romania',
    'SK' => 'Slovakia',
    'SI' => 'Slovenia',
    'ES' => 'Spain',
    'SE' => 'Sweden',

    // Other common countries
    'GB' => 'United Kingdom',
    'US' => 'United States',
    'CA' => 'Canada',
    'AU' => 'Australia',
    'NZ' => 'New Zealand',
    'CH' => 'Switzerland',
    'NO' => 'Norway',
    'IS' => 'Iceland',
    'JP' => 'Japan',
    'CN' => 'China',
    'IN' => 'India',
    'BR' => 'Brazil',
    'MX' => 'Mexico',
    'AR' => 'Argentina',
    'ZA' => 'South Africa',
    'EG' => 'Egypt',
    'AE' => 'United Arab Emirates',
    'SA' => 'Saudi Arabia',
    'TR' => 'Turkey',
    'RU' => 'Russia',
    'UA' => 'Ukraine',
    'BY' => 'Belarus',
    'RS' => 'Serbia',
    'BA' => 'Bosnia and Herzegovina',
    'MK' => 'North Macedonia',
    'AL' => 'Albania',
    'ME' => 'Montenegro',
    'XK' => 'Kosovo',
    'MD' => 'Moldova',
    'GE' => 'Georgia',
    'AM' => 'Armenia',
    'AZ' => 'Azerbaijan',
    'KZ' => 'Kazakhstan',
    'IL' => 'Israel',
    'JO' => 'Jordan',
    'LB' => 'Lebanon',
    'IQ' => 'Iraq',
    'IR' => 'Iran',
    'PK' => 'Pakistan',
    'BD' => 'Bangladesh',
    'TH' => 'Thailand',
    'VN' => 'Vietnam',
    'PH' => 'Philippines',
    'ID' => 'Indonesia',
    'MY' => 'Malaysia',
    'SG' => 'Singapore',
    'KR' => 'South Korea',
    'TW' => 'Taiwan',
    'HK' => 'Hong Kong',
];

